// js/utils/ids.js
// Booking IDs generated by this app are 'b' + creation-time-in-base36 (8
// chars) + 12 random chars = 21 chars total.
//
// DO NOT sort ids by plain string comparison. An earlier version did, on the
// assumption that every id shares that structure — it does not. Rows created
// before this scheme have ids like 'z5darnfgby11...' and 'yvgwqy26yjzt...'
// with no 'b' prefix, and lexicographically 'z' > 'y' > 'b' always. So every
// legacy row outranked every app-created row in a descending id sort,
// permanently, which is why "Recently Added" kept showing the same old rows
// at the top no matter what was booked. Use creationMs() below instead.

export function genId() {
  const ts = Date.now().toString(36);
  const rand = Array.from(crypto.getRandomValues(new Uint8Array(10)))
    .map(b => b.toString(36).padStart(2, '0')).join('').slice(0, 12);
  return 'b' + ts + rand;
}

// Creation time in epoch ms, decoded from the id. Returns -1 for any id not
// produced by genId() (legacy rows), since their creation time genuinely
// cannot be recovered from the id — callers should treat -1 as "oldest".
//
// The proper long-term fix is a real `created_at timestamptz default now()`
// column on public.bookings; this decoder exists because the id is currently
// the only creation-time signal available for existing data.
export function creationMs(id) {
  const head = String(id || '').slice(0, 9);
  if (!/^b[0-9a-z]{8}$/.test(head)) return -1;
  const ms = parseInt(head.slice(1), 36);
  return Number.isFinite(ms) ? ms : -1;
}
